print("HEY I START MY PYTHON JOURNEY")  
print(12)
print(12 + 12)
print("12 + 12 =")


#PRINT IS A FUNCTION THAT ALLOWS YOU TO PRINT TEXT OR VARIABLES TO THE CONSOLE. IT IS ONE OF THE MOST BASIC AND COMMONLY USED FUNCTIONS IN PYTHON.